version: '3.1'
volumes:
  node_modules:
services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/home/
      - node_modules:/home/node_modules
    depends_on:
      - redis
      - memcached
    command: tail -F anything
  redis:
    image: "redis:alpine"
  memcached:
    image: "memcached:alpine"
    ports:
      - 11211:11211
